### ISSUE TITLE
AppBarの見た目変更

### ISSUE THREAD

**Issue by ten66** [recursion-group-m/oekaki-app#67]

**Comment by Yuta-K19418** [comment]
AppBar無理して使わなくてもいいですよ。ten先生に任せます 笑

**Comment by ten66** [comment]
> AppBar無理して使わなくてもいいですよ。ten先生に任せます 笑
<img width="1139" alt="スクリーンショット 2022-01-25 19 45 31" src="https://user-images.githubusercontent.com/95117796/150962845-b663ef03-4d90-4e01-a15f-8f569822e6bd.png">
こんな感じにしたのですが、僕も正直言うと「これ必要かな？」って思いながら実装してたので、いっその事AppBar.tsx削除してもいいですか？笑
また必要そうならすぐ追加できそうですし。笑

**Comment by Yuta-K19418** [comment]
消してもOKですよ!笑
